export const plans = [
    {
        id: 'free',
        name: 'Individual',
        price: 'Free',
        description: 'For exploration & local testing.',
        features: [
            '50 requests / day quota',
            'Ollama (local models) access',
            'Basic Semantic Cache',
            'MCP Adapter Support',
            'Community support',
        ],
        cta: 'Current Plan',
        active: true,
    },
    {
        id: 'pro',
        name: 'Pro',
        price: '$29',
        priceDetail: '/mo + PAYG usage',
        description: 'For growing teams and production workflows.',
        features: [
            '100 RPM rate limit',
            'All LLM Providers (OpenAI, Anthropic, Gemini)',
            'Sub-millisecond semantic cache',
            'PAYG token top-up included',
            'Priority email support',
        ],
        cta: 'Upgrade to Pro',
        active: false,
        highlight: true,
    },
    {
        id: 'business',
        name: 'Business',
        price: '$99',
        priceDetail: '/mo + PAYG usage',
        description: 'Enterprise routing, RBAC, and analytics.',
        features: [
            '1000+ RPM rate limit',
            'Full RBAC enforcement',
            'Multi-org management',
            'Deep analytics & audit logs',
            'Dedicated SLA & volume discounts',
        ],
        cta: 'Upgrade to Business',
        active: false,
    },
]