// proto/router.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: router.proto

package router

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticRouter_SelectTools_FullMethodName  = "/router.SemanticRouter/SelectTools"
	SemanticRouter_RegisterTool_FullMethodName = "/router.SemanticRouter/RegisterTool"
)

// SemanticRouterClient is the client API for SemanticRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SemanticRouterClient interface {
	// Selects the most relevant tools for a given user prompt
	SelectTools(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error)
	// Registers or updates a tool in the vector database
	RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error)
}

type semanticRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticRouterClient(cc grpc.ClientConnInterface) SemanticRouterClient {
	return &semanticRouterClient{cc}
}

func (c *semanticRouterClient) SelectTools(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*ToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolResponse)
	err := c.cc.Invoke(ctx, SemanticRouter_SelectTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticRouterClient) RegisterTool(ctx context.Context, in *RegisterToolRequest, opts ...grpc.CallOption) (*RegisterToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterToolResponse)
	err := c.cc.Invoke(ctx, SemanticRouter_RegisterTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticRouterServer is the server API for SemanticRouter service.
// All implementations must embed UnimplementedSemanticRouterServer
// for forward compatibility.
type SemanticRouterServer interface {
	// Selects the most relevant tools for a given user prompt
	SelectTools(context.Context, *ToolRequest) (*ToolResponse, error)
	// Registers or updates a tool in the vector database
	RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error)
	mustEmbedUnimplementedSemanticRouterServer()
}

// UnimplementedSemanticRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticRouterServer struct{}

func (UnimplementedSemanticRouterServer) SelectTools(context.Context, *ToolRequest) (*ToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectTools not implemented")
}
func (UnimplementedSemanticRouterServer) RegisterTool(context.Context, *RegisterToolRequest) (*RegisterToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTool not implemented")
}
func (UnimplementedSemanticRouterServer) mustEmbedUnimplementedSemanticRouterServer() {}
func (UnimplementedSemanticRouterServer) testEmbeddedByValue()                        {}

// UnsafeSemanticRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticRouterServer will
// result in compilation errors.
type UnsafeSemanticRouterServer interface {
	mustEmbedUnimplementedSemanticRouterServer()
}

func RegisterSemanticRouterServer(s grpc.ServiceRegistrar, srv SemanticRouterServer) {
	// If the following call panics, it indicates UnimplementedSemanticRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticRouter_ServiceDesc, srv)
}

func _SemanticRouter_SelectTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticRouterServer).SelectTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticRouter_SelectTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticRouterServer).SelectTools(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticRouter_RegisterTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticRouterServer).RegisterTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticRouter_RegisterTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticRouterServer).RegisterTool(ctx, req.(*RegisterToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticRouter_ServiceDesc is the grpc.ServiceDesc for SemanticRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "router.SemanticRouter",
	HandlerType: (*SemanticRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectTools",
			Handler:    _SemanticRouter_SelectTools_Handler,
		},
		{
			MethodName: "RegisterTool",
			Handler:    _SemanticRouter_RegisterTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}
