// proto/router.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/router.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OrgId         string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterToolRequest) Reset() {
	*x = RegisterToolRequest{}
	mi := &file_proto_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterToolRequest) ProtoMessage() {}

func (x *RegisterToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterToolRequest.ProtoReflect.Descriptor instead.
func (*RegisterToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterToolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterToolRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterToolRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterToolRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type RegisterToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterToolResponse) Reset() {
	*x = RegisterToolResponse{}
	mi := &file_proto_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterToolResponse) ProtoMessage() {}

func (x *RegisterToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterToolResponse.ProtoReflect.Descriptor instead.
func (*RegisterToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterToolResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ToolRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Prompt                 string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	UserId                 string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllowedToolIds         []string               `protobuf:"bytes,3,rep,name=allowed_tool_ids,json=allowedToolIds,proto3" json:"allowed_tool_ids,omitempty"`                           // For RBAC-filtered searches
	ScoreThresholdOverride float32                `protobuf:"fixed32,4,opt,name=score_threshold_override,json=scoreThresholdOverride,proto3" json:"score_threshold_override,omitempty"` // Override default relevance threshold
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_proto_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{2}
}

func (x *ToolRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ToolRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ToolRequest) GetAllowedToolIds() []string {
	if x != nil {
		return x.AllowedToolIds
	}
	return nil
}

func (x *ToolRequest) GetScoreThresholdOverride() float32 {
	if x != nil {
		return x.ScoreThresholdOverride
	}
	return 0
}

type Tool struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RelevanceScore float32                `protobuf:"fixed32,3,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"` // Tool description from Qdrant
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_proto_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{3}
}

func (x *Tool) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ToolResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tools             []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	TotalTokensSaved  int32                  `protobuf:"varint,2,opt,name=total_tokens_saved,json=totalTokensSaved,proto3" json:"total_tokens_saved,omitempty"`
	CompressedPrompt  string                 `protobuf:"bytes,3,opt,name=compressed_prompt,json=compressedPrompt,proto3" json:"compressed_prompt,omitempty"`
	SimilarPromptHash string                 `protobuf:"bytes,4,opt,name=similar_prompt_hash,json=similarPromptHash,proto3" json:"similar_prompt_hash,omitempty"` // Hash of a previously seen similar prompt (if any)
	CurrentPromptHash string                 `protobuf:"bytes,5,opt,name=current_prompt_hash,json=currentPromptHash,proto3" json:"current_prompt_hash,omitempty"` // Canonical hash of the incoming prompt
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_proto_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{4}
}

func (x *ToolResponse) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ToolResponse) GetTotalTokensSaved() int32 {
	if x != nil {
		return x.TotalTokensSaved
	}
	return 0
}

func (x *ToolResponse) GetCompressedPrompt() string {
	if x != nil {
		return x.CompressedPrompt
	}
	return ""
}

func (x *ToolResponse) GetSimilarPromptHash() string {
	if x != nil {
		return x.SimilarPromptHash
	}
	return ""
}

func (x *ToolResponse) GetCurrentPromptHash() string {
	if x != nil {
		return x.CurrentPromptHash
	}
	return ""
}

type ToolChainRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Prompt                 string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	UserId                 string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllowedToolIds         []string               `protobuf:"bytes,3,rep,name=allowed_tool_ids,json=allowedToolIds,proto3" json:"allowed_tool_ids,omitempty"`
	ScoreThresholdOverride float32                `protobuf:"fixed32,4,opt,name=score_threshold_override,json=scoreThresholdOverride,proto3" json:"score_threshold_override,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ToolChainRequest) Reset() {
	*x = ToolChainRequest{}
	mi := &file_proto_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolChainRequest) ProtoMessage() {}

func (x *ToolChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolChainRequest.ProtoReflect.Descriptor instead.
func (*ToolChainRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{5}
}

func (x *ToolChainRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ToolChainRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ToolChainRequest) GetAllowedToolIds() []string {
	if x != nil {
		return x.AllowedToolIds
	}
	return nil
}

func (x *ToolChainRequest) GetScoreThresholdOverride() float32 {
	if x != nil {
		return x.ScoreThresholdOverride
	}
	return 0
}

type ToolStep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StepOrder      int32                  `protobuf:"varint,1,opt,name=step_order,json=stepOrder,proto3" json:"step_order,omitempty"`
	ToolName       string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ParametersJson string                 `protobuf:"bytes,3,opt,name=parameters_json,json=parametersJson,proto3" json:"parameters_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolStep) Reset() {
	*x = ToolStep{}
	mi := &file_proto_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStep) ProtoMessage() {}

func (x *ToolStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStep.ProtoReflect.Descriptor instead.
func (*ToolStep) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{6}
}

func (x *ToolStep) GetStepOrder() int32 {
	if x != nil {
		return x.StepOrder
	}
	return 0
}

func (x *ToolStep) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolStep) GetParametersJson() string {
	if x != nil {
		return x.ParametersJson
	}
	return ""
}

type ToolChainResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Steps           []*ToolStep            `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	ConfidenceScore float32                `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToolChainResponse) Reset() {
	*x = ToolChainResponse{}
	mi := &file_proto_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolChainResponse) ProtoMessage() {}

func (x *ToolChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolChainResponse.ProtoReflect.Descriptor instead.
func (*ToolChainResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{7}
}

func (x *ToolChainResponse) GetSteps() []*ToolStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ToolChainResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

var File_proto_router_proto protoreflect.FileDescriptor

const file_proto_router_proto_rawDesc = "" +
	"\n" +
	"\x12proto/router.proto\x12\x06router\"r\n" +
	"\x13RegisterToolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\"F\n" +
	"\x14RegisterToolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa2\x01\n" +
	"\vToolRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12(\n" +
	"\x10allowed_tool_ids\x18\x03 \x03(\tR\x0eallowedToolIds\x128\n" +
	"\x18score_threshold_override\x18\x04 \x01(\x02R\x16scoreThresholdOverride\"u\n" +
	"\x04Tool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0frelevance_score\x18\x03 \x01(\x02R\x0erelevanceScore\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xed\x01\n" +
	"\fToolResponse\x12\"\n" +
	"\x05tools\x18\x01 \x03(\v2\f.router.ToolR\x05tools\x12,\n" +
	"\x12total_tokens_saved\x18\x02 \x01(\x05R\x10totalTokensSaved\x12+\n" +
	"\x11compressed_prompt\x18\x03 \x01(\tR\x10compressedPrompt\x12.\n" +
	"\x13similar_prompt_hash\x18\x04 \x01(\tR\x11similarPromptHash\x12.\n" +
	"\x13current_prompt_hash\x18\x05 \x01(\tR\x11currentPromptHash\"\xa7\x01\n" +
	"\x10ToolChainRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12(\n" +
	"\x10allowed_tool_ids\x18\x03 \x03(\tR\x0eallowedToolIds\x128\n" +
	"\x18score_threshold_override\x18\x04 \x01(\x02R\x16scoreThresholdOverride\"o\n" +
	"\bToolStep\x12\x1d\n" +
	"\n" +
	"step_order\x18\x01 \x01(\x05R\tstepOrder\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12'\n" +
	"\x0fparameters_json\x18\x03 \x01(\tR\x0eparametersJson\"f\n" +
	"\x11ToolChainResponse\x12&\n" +
	"\x05steps\x18\x01 \x03(\v2\x10.router.ToolStepR\x05steps\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore2\xdb\x01\n" +
	"\x0eSemanticRouter\x128\n" +
	"\vSelectTools\x12\x13.router.ToolRequest\x1a\x14.router.ToolResponse\x12I\n" +
	"\fRegisterTool\x12\x1b.router.RegisterToolRequest\x1a\x1c.router.RegisterToolResponse\x12D\n" +
	"\rPlanToolChain\x12\x18.router.ToolChainRequest\x1a\x19.router.ToolChainResponseB=Z;github.com/Opsylux/memzent/services/gateway/internal/routerb\x06proto3"

var (
	file_proto_router_proto_rawDescOnce sync.Once
	file_proto_router_proto_rawDescData []byte
)

func file_proto_router_proto_rawDescGZIP() []byte {
	file_proto_router_proto_rawDescOnce.Do(func() {
		file_proto_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_router_proto_rawDesc), len(file_proto_router_proto_rawDesc)))
	})
	return file_proto_router_proto_rawDescData
}

var file_proto_router_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_router_proto_goTypes = []any{
	(*RegisterToolRequest)(nil),  // 0: router.RegisterToolRequest
	(*RegisterToolResponse)(nil), // 1: router.RegisterToolResponse
	(*ToolRequest)(nil),          // 2: router.ToolRequest
	(*Tool)(nil),                 // 3: router.Tool
	(*ToolResponse)(nil),         // 4: router.ToolResponse
	(*ToolChainRequest)(nil),     // 5: router.ToolChainRequest
	(*ToolStep)(nil),             // 6: router.ToolStep
	(*ToolChainResponse)(nil),    // 7: router.ToolChainResponse
}
var file_proto_router_proto_depIdxs = []int32{
	3, // 0: router.ToolResponse.tools:type_name -> router.Tool
	6, // 1: router.ToolChainResponse.steps:type_name -> router.ToolStep
	2, // 2: router.SemanticRouter.SelectTools:input_type -> router.ToolRequest
	0, // 3: router.SemanticRouter.RegisterTool:input_type -> router.RegisterToolRequest
	5, // 4: router.SemanticRouter.PlanToolChain:input_type -> router.ToolChainRequest
	4, // 5: router.SemanticRouter.SelectTools:output_type -> router.ToolResponse
	1, // 6: router.SemanticRouter.RegisterTool:output_type -> router.RegisterToolResponse
	7, // 7: router.SemanticRouter.PlanToolChain:output_type -> router.ToolChainResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_router_proto_init() }
func file_proto_router_proto_init() {
	if File_proto_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_router_proto_rawDesc), len(file_proto_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_router_proto_goTypes,
		DependencyIndexes: file_proto_router_proto_depIdxs,
		MessageInfos:      file_proto_router_proto_msgTypes,
	}.Build()
	File_proto_router_proto = out.File
	file_proto_router_proto_goTypes = nil
	file_proto_router_proto_depIdxs = nil
}
